# Generated by Django 3.1.2 on 2020-12-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201203_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('R&I', 'R&I'), ('전략마케팅', '전략마케팅')], default=1, max_length=10, verbose_name='소속'),
            preserve_default=False,
        ),
    ]
