# Generated by Django 3.1.2 on 2020-11-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201109_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='export_country',
        ),
        migrations.AddField(
            model_name='post',
            name='export_country',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
