# Generated by Django 3.1.2 on 2020-11-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201109_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='export_country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='수출 국가를 입력하세요.', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='export_country',
        ),
    ]
