# Generated by Django 3.1.2 on 2020-11-09 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201109_1344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='export_country',
            new_name='Category2',
        ),
    ]
