# Generated by Django 3.1.2 on 2020-11-09 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201109_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='country',
            field=models.ForeignKey(default=1, help_text='수출 국가를 설정하세요.', on_delete=django.db.models.deletion.CASCADE, to='blog.category2'),
            preserve_default=False,
        ),
    ]
