# Generated by Django 3.1.2 on 2020-11-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='country',
        ),
        migrations.AddField(
            model_name='post',
            name='country',
            field=models.ManyToManyField(help_text='수출 국가를 설정하세요.', to='blog.Category2'),
        ),
    ]
