# Generated by Django 3.1.2 on 2020-11-09 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20201109_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='country',
        ),
        migrations.DeleteModel(
            name='Category2',
        ),
    ]
