# Generated by Django 3.1.2 on 2020-11-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20201109_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='export_country',
            field=models.CharField(choices=[('미확인', '미확인'), ('가능', '가능'), ('불가능', '불가능'), ('조건부가능', '조건부가능')], default=1, max_length=6),
            preserve_default=False,
        ),
    ]
