# Generated by Django 3.1.2 on 2020-11-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_export_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='export_country',
            new_name='export_china',
        ),
        migrations.AddField(
            model_name='post',
            name='patent',
            field=models.CharField(choices=[('유', '유'), ('무', '무')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='reward',
            field=models.CharField(choices=[('유', '유'), ('무', '무')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='thesis',
            field=models.CharField(choices=[('유', '유'), ('무', '무')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
