# Generated by Django 3.1.2 on 2020-11-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='patent_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='reward_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='thesis_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
