# Generated by Django 3.1.2 on 2020-11-10 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20201110_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='main_benefit',
        ),
    ]
