# Generated by Django 3.1.2 on 2020-11-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_post_main_benefit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='efficacy_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
