# Generated by Django 3.1.2 on 2020-12-08 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0026_auto_20201208_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(help_text='글의 분류를 설정하세요.', to='blog.Category', verbose_name='효능 카테고리'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='주요 내용'),
        ),
        migrations.AlterField(
            model_name='post',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일자'),
        ),
        migrations.AlterField(
            model_name='post',
            name='efficacy_image',
            field=models.ImageField(default='media/default_image.jpg', upload_to='', verbose_name='효능/임상 이미지'),
        ),
        migrations.AlterField(
            model_name='post',
            name='export_china',
            field=models.CharField(choices=[('미확인', '미확인'), ('가능', '가능'), ('불가능', '불가능'), ('조건부가능', '조건부가능')], max_length=6, verbose_name='중국수출여부'),
        ),
        migrations.AlterField(
            model_name='post',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL, verbose_name='북마크'),
        ),
        migrations.AlterField(
            model_name='post',
            name='inci_name',
            field=models.CharField(max_length=200, verbose_name='INCI명'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ingredient',
            field=models.CharField(max_length=200, verbose_name='국문명'),
        ),
        migrations.AlterField(
            model_name='post',
            name='patent',
            field=models.CharField(choices=[('유', '유'), ('무', '무')], max_length=2, verbose_name='특허 유/무'),
        ),
        migrations.AlterField(
            model_name='post',
            name='patent_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='특허 번호'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reward',
            field=models.CharField(choices=[('유', '유'), ('무', '무')], max_length=2, verbose_name='수상 유/무'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reward_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='수상명'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tentative_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='가칭명'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thesis',
            field=models.CharField(choices=[('유', '유'), ('무', '무')], max_length=2, verbose_name='논문 유/무'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thesis_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='논문명'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='대표 이미지'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updateDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='수정일자'),
        ),
    ]
