# Generated by Django 3.1.2 on 2020-12-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20201208_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_image',
            field=models.ImageField(blank=True, default='media/default_image.jpg', upload_to='', verbose_name='대표 이미지'),
        ),
    ]
