# Generated by Django 3.1.2 on 2020-12-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20201208_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='efficacy_image',
            field=models.ImageField(default='default_image.jpg', upload_to='', verbose_name='효능/임상 이미지'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_image',
            field=models.ImageField(blank=True, default='default_image.jpg', upload_to='', verbose_name='대표 이미지'),
        ),
    ]
