# Generated by Django 3.1.2 on 2020-12-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20201208_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='efficacy_image',
            field=models.ImageField(blank=True, default='default_image.jpg', upload_to='', verbose_name='효능/임상 이미지'),
        ),
    ]
