# Generated by Django 3.1.2 on 2020-12-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20201208_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_image',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='title_images/', verbose_name='대표 이미지'),
        ),
    ]
